<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>LauncherUiPreview</AssemblyName>
    <RootNamespace>LauncherUiPreview</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/STS2Mobile/STS2Mobile.csproj" />
    <Reference Include="0Harmony">
      <HintPath>../../upstream/godot-export/.godot/mono/publish/arm64/0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>../../android/assets/dotnet_bcl/Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Content Include="../../android/assets/dotnet_bcl/Mono.Cecil.dll">
      <Link>Mono.Cecil.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Reference Include="MonoMod.Backports">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Backports.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Core">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Iced">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Iced.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.ILHelpers">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.ILHelpers.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Utils.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>../../upstream/godot-export/.godot/mono/publish/arm64/sts2.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
