function Add-SteamVersionSelectionBranchEvidenceDocsChecks {
    Add-Check `
        "docs\steam-version-selection-evidence-template.md" `
        "captures branch validation evidence" `
        @(
            "Selector mode",
            "Branch discovery",
            "Android credential provider model",
            "Launcher stores Steam password for credential providers",
            "SteamKit debug logs opt-in status",
            "disabled by default",
            "Steam branch dropdown option metadata",
            "Static guardrails",
            "steam-version-selection-release-readiness\.md",
            "audit-steam-version-selection\.ps1",
            "audit-steam-branch-guidance-parity\.ps1",
            "blocked states",
            "Selector helper text shows the active install slot",
            "selected game version note",
            "selected game version slot kind",
            "Native pre-routing logs selected branch",
            "selected branch note",
            "branch switch marker filename",
            "Branch switch marker records",
            "parseable UTC",
            "required-evidence status",
            "Branch switch previous branch",
            "Branch switch selected branch",
            "Branch switch selected version",
            "Branch switch selected version slot kind",
            "Branch switch selected version slot directory",
            "Branch switch selected branch matches current selected branch",
            "Branch switch selected branch note",
            "Branch switch local backup forced",
            "Branch switch manual Push requires backup storage",
            "Branch switch warning acknowledged",
            "Branch switch non-public warning acknowledged",
            "Branch switch marker has required safety evidence",
            "Branch switch marker has required safety evidence for selected branch",
            "Branch-switch manual Push prerequisites satisfied",
            "Pre-Push local backup evidence count",
            "Pre-Push cloud backup evidence count",
            "Latest pre-Push local backup UTC",
            "Latest pre-Push cloud backup UTC",
            "Pre-Push local backup evidence after branch switch",
            "Pre-Push cloud backup evidence after branch switch",
            "Branch-switch pre-Push backup evidence satisfied",
            "Manual Pull evidence marker filename",
            "Manual Push evidence marker filename",
            "last_manual_cloud_push_blocked\.txt",
            "Manual Pull evidence marker filename",
            "Manual Pull evidence marker path",
            "Manual Pull evidence UTC",
            "Manual Pull evidence UTC parseable",
            "Manual Pull evidence selected branch",
            "Manual Pull evidence selected version",
            "Manual Pull evidence selected version slot kind",
            "Manual Pull evidence selected version slot directory",
            "Manual Pull completion flag recorded",
            "Manual Pull completed before Push",
            "Manual Pull evidence is after branch switch",
            "Manual Pull evidence matches selected branch",
            "Manual Pull completed after branch switch",
            "Current important Android local save evidence count",
            "Current important Android local save evidence present",
            "Baseline manual Push prerequisites satisfied",
            "Manual Push evidence marker filename",
            "Manual Push evidence marker path",
            "Manual Push evidence UTC",
            "Latest manual Push evidence outcome",
            "Latest manual Push evidence UTC",
            "Latest manual Push evidence selected branch",
            "Latest manual Push evidence selected version",
            "Latest manual Push evidence selected version slot kind",
            "Latest manual Push evidence selected version slot directory",
            "Latest manual Push evidence reason",
            "Manual Push evidence UTC parseable",
            "Manual Push evidence selected branch",
            "Manual Push evidence selected version",
            "Manual Push evidence selected version slot kind",
            "Manual Push evidence selected version slot directory",
            "Manual Push evidence recorded local backup count",
            "Manual Push evidence recorded cloud backup count",
            "Manual Push evidence recorded latest local backup UTC",
            "Manual Push evidence recorded latest cloud backup UTC",
            "Manual Push evidence recorded important local save evidence count",
            "Manual Push evidence recorded baseline prerequisites satisfied",
            "Manual Push completion flag recorded",
            "Manual Push evidence is after branch switch",
            "Manual Push evidence matches selected branch",
            "Manual Push evidence recorded pre-Push backup evidence satisfied",
            "Manual Push completed after branch switch for selected version with backup evidence",
            "Manual Push blocked evidence marker filename",
            "Manual Push blocked evidence marker path",
            "Manual Push blocked evidence UTC",
            "Manual Push blocked evidence UTC parseable",
            "Manual Push blocked evidence selected branch",
            "Manual Push blocked evidence selected version",
            "Manual Push blocked evidence selected version slot kind",
            "Manual Push blocked evidence selected version slot directory",
            "Manual Push blocked evidence matches selected branch",
            "Manual Push blocked evidence recorded prerequisites satisfied",
            "Manual Push blocked evidence recorded local backup count",
            "Manual Push blocked evidence recorded cloud backup count",
            "Manual Push blocked evidence recorded latest local backup UTC",
            "Manual Push blocked evidence recorded latest cloud backup UTC",
            "Manual Push blocked evidence recorded important local save evidence count",
            "Manual Push blocked evidence recorded baseline prerequisites satisfied",
            "Manual Push blocked evidence recorded pre-Push backup evidence satisfied",
            "Manual Push blocked evidence reason",
            "Manual Push blocked before upload evidence recorded",
            "Early branch-switch Push gate blocks",
            "local/cloud pre-Push backup counts",
            "latest local/cloud backup UTC",
            "every important Android local save",
            "every existing important Steam Cloud save",
            "selected-cache-preserved aggregate",
            "Steam beta password",
            "save compatibility",
            "Artifact hygiene",
            "Steam credentials",
            "refresh tokens",
            "shared preferences",
            "device identifiers",
            "Raw full logcat was omitted by default",
            "IncludeRawLogcat",
            "sts2_steamkit_debug_logs",
            "logcat-steam-version-focused-redacted\.txt",
            "best-effort redacted file was manually reviewed before posting",
            "Redacted focused logcat includes its best-effort/manual-review warning header",
            "ARTIFACT_HYGIENE\.txt",
            "raw logs are treated as local-only",
            "PUBLIC_SHARE_MANIFEST\.txt",
            "preferred public artifacts",
            "logcat-redaction-summary\.txt",
            "focused-line and changed-line counts",
            "launcher-diagnostics-index\.txt",
            "full launcher diagnostics report attached publicly was manually reviewed/redacted",
            "Full launcher diagnostics and startup-recovery diagnostics reports include a public-sharing warning"
        )
}
