function Add-SteamVersionSelectionDiagnosticsReportingLauncherPreferenceChecks {
    Add-Check `
        "src\STS2Mobile\Launcher\LauncherDiagnostics.ReportLauncherPreferences.cs" `
        "reports selected branch, credential, portal UX, and selected branch marker state" `
        @(
            "Selected game branch",
            "Selected game branch preference key",
            "Selected game branch source",
            "Selected game branch selection kind",
            "Selected game version note",
            "Steam branch selector mode",
            "Steam beta password entry supported",
            "Android credential provider model",
            "Native credential panel inline status configured",
            "Native credential panel keyboard-safe layout configured",
            "Native credential panel touch-target layout configured",
            "Native credential panel large field targets supported",
            "Native credential panel requests both Autofill fields",
            "Native credential panel focus Autofill requests supported",
            "Native credential panel task-led buttons supported",
            "Native credential panel responsive action rows supported",
            "Native credential panel orientation reflow supported",
            "Native credential panel short-height copy supported",
            "Native credential panel short-height reflow supported",
            "Native credential panel IME height reflow supported",
            "Native credential panel password visibility toggle supported",
            "Steam Guard one-shot code guidance supported",
            "Steam Guard alphanumeric keyboard supported",
            "Failed-login retry guidance supported",
            "Context-specific login recovery guidance supported",
            "Godot login field credential metadata configured",
            "Android keyboard credential hints configured",
            "Godot fields are native Android Autofill targets",
            "Password-manager suggestions device validated",
            "Native credential handoff popup supported",
            "Launcher stores Steam password for credential providers",
            "Native credential handoff result TTL seconds",
            "Android credential provider implementation note",
            "Android credential provider capability boundary",
            "Launcher portal UX model",
            "AppendLauncherPortalUxFeatureReports",
            "Launcher portal UX implementation note",
            "Launcher portal UX validation boundary",
            "SteamKit debug logs opt-in enabled",
            "SteamKit debug logs sanitized for credentials/tokens",
            "Selected game version slot kind",
            "Selected game version slot directory",
            "Selected game branch marker install slot kind",
            "Selected game branch marker install slot directory",
            "Selected game branch marker expected install slot kind",
            "Selected game branch marker expected install slot directory",
            "Selected game branch marker has matching install slot provenance",
            "Selected game branch marker has depot manifests",
            "Selected game branch marker depot manifest entries",
            "Selected game branch marker ready",
            "AppendBranchAvailability",
            "AppendBranchSwitchSafety",
            "AppendCachedGameVersions"
        )
}
