function Add-SteamVersionSelectionBranchEvidenceCloudPushChecks {
    Add-Check `
        "docs\steam-version-selection-evidence-template.md" `
        "captures manual Pull, Push, blocked-Push, and cache preservation evidence" `
        @(
            "Manual Pull evidence marker filename",
            "Manual Push evidence marker filename",
            "last_manual_cloud_push_blocked\.txt",
            "Manual Pull evidence marker filename",
            "Manual Pull evidence marker path",
            "Manual Pull evidence UTC",
            "Manual Pull evidence UTC parseable",
            "Manual Pull evidence selected branch",
            "Manual Pull evidence selected version",
            "Manual Pull evidence selected version slot kind",
            "Manual Pull evidence selected version slot directory",
            "Manual Pull completion flag recorded",
            "Manual Pull completed before Push",
            "Manual Pull evidence is after branch switch",
            "Manual Pull evidence matches selected branch",
            "Manual Pull completed after branch switch",
            "Current important Android local save evidence count",
            "Current important Android local save evidence present",
            "Baseline manual Push prerequisites satisfied",
            "Manual Push evidence marker filename",
            "Manual Push evidence marker path",
            "Manual Push evidence UTC",
            "Latest manual Push evidence outcome",
            "Latest manual Push evidence UTC",
            "Latest manual Push evidence selected branch",
            "Latest manual Push evidence selected version",
            "Latest manual Push evidence selected version slot kind",
            "Latest manual Push evidence selected version slot directory",
            "Latest manual Push evidence reason",
            "Manual Push evidence UTC parseable",
            "Manual Push evidence selected branch",
            "Manual Push evidence selected version",
            "Manual Push evidence selected version slot kind",
            "Manual Push evidence selected version slot directory",
            "Manual Push evidence recorded local backup count",
            "Manual Push evidence recorded cloud backup count",
            "Manual Push evidence recorded latest local backup UTC",
            "Manual Push evidence recorded latest cloud backup UTC",
            "Manual Push evidence recorded important local save evidence count",
            "Manual Push evidence recorded baseline prerequisites satisfied",
            "Manual Push completion flag recorded",
            "Manual Push evidence is after branch switch",
            "Manual Push evidence matches selected branch",
            "Manual Push evidence recorded pre-Push backup evidence satisfied",
            "Manual Push completed after branch switch for selected version with backup evidence",
            "Manual Push blocked evidence marker filename",
            "Manual Push blocked evidence marker path",
            "Manual Push blocked evidence UTC",
            "Manual Push blocked evidence UTC parseable",
            "Manual Push blocked evidence selected branch",
            "Manual Push blocked evidence selected version",
            "Manual Push blocked evidence selected version slot kind",
            "Manual Push blocked evidence selected version slot directory",
            "Manual Push blocked evidence matches selected branch",
            "Manual Push blocked evidence recorded prerequisites satisfied",
            "Manual Push blocked evidence recorded local backup count",
            "Manual Push blocked evidence recorded cloud backup count",
            "Manual Push blocked evidence recorded latest local backup UTC",
            "Manual Push blocked evidence recorded latest cloud backup UTC",
            "Manual Push blocked evidence recorded important local save evidence count",
            "Manual Push blocked evidence recorded baseline prerequisites satisfied",
            "Manual Push blocked evidence recorded pre-Push backup evidence satisfied",
            "Manual Push blocked evidence reason",
            "Manual Push blocked before upload evidence recorded",
            "Early branch-switch Push gate blocks",
            "local/cloud pre-Push backup counts",
            "latest local/cloud backup UTC",
            "every important Android local save",
            "every existing important Steam Cloud save",
            "selected-cache-preserved aggregate"
        )
}
