function Add-SteamVersionSelectionLoginPortalEvidenceDocsValidationMatrixPortalWorkflowChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures launcher portal status, workflow, and responsive layout validation evidence" `
        @(
            "Launcher portal UX model",
            "Launcher phase-labeled status supported",
            "Launcher structured status chip supported",
            "Launcher guided next-action status supported",
            "Launcher error-first guided status supported",
            "Launcher safe first-run guidance supported",
            "Launcher compact safe-flow guidance collapsible",
            "Launcher compact low-profile safe-flow toggle supported",
            "Launcher compact safe-flow toggle detail labels supported",
            "Launcher compact structured safe-flow toggle labels supported",
            "Launcher compact safe-flow bounded guide supported",
            "Launcher compact active-task safe-flow suppression supported",
            "Launcher mobile-first compact layout supported",
            "Launcher compact dense panel padding supported",
            "Launcher compact dense vertical rhythm supported",
            "Launcher rounded scaled metrics supported",
            "Launcher Android compact touch-scale floor supported",
            "Launcher Android-readable warmup screen supported",
            "Launcher Android-readable startup status card supported",
            "Launcher compact dynamic content width supported",
            "Launcher tablet/wide content layout supported",
            "Launcher top-anchored portal content supported",
            "Launcher compact vertical status hero supported",
            "Launcher compact low-profile status card supported",
            "Launcher compact status headline row supported",
            "Launcher compact short status details supported",
            "Launcher compact stacked status headline supported",
            "Launcher viewport-aware compact status headline reflow supported",
            "Launcher compact stable status detail row supported",
            "Launcher stable destination navigation supported",
            "Launcher Home destination supported",
            "Launcher Saves destination supported",
            "Launcher Versions destination supported",
            "Launcher Mods destination supported",
            "Launcher Help destination supported",
            "Launcher phone bottom navigation supported",
            "Launcher wide/foldable top navigation supported",
            "Launcher destination-owned action groups supported",
            "Launcher deterministic destination scroll reset supported",
            "Launcher dynamic task re-anchor removed",
            "Launcher touch-safe destination controls supported",
            "Launcher Android display safe-area insets supported",
            "Launcher Android bottom-navigation safe-area spacer supported",
            "Launcher Android composition refresh supported",
            "Launcher keyboard-focused input scroll supported"
        )
}
