function Add-SteamVersionSelectionLoginPortalEvidenceDocsValidationMatrixPortalWorkflowChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures launcher portal status, workflow, and responsive layout validation evidence" `
        @(
            "Launcher portal UX model",
            "Launcher phase-labeled status supported",
            "Launcher structured status chip supported",
            "Launcher guided next-action status supported",
            "Launcher error-first guided status supported",
            "Launcher safe first-run guidance supported",
            "Launcher compact safe-flow guidance collapsible",
            "Launcher compact low-profile safe-flow toggle supported",
            "Launcher compact safe-flow toggle detail labels supported",
            "Launcher compact structured safe-flow toggle labels supported",
            "Launcher compact safe-flow bounded guide supported",
            "Launcher compact active-task safe-flow suppression supported",
            "Launcher mobile-first compact layout supported",
            "Launcher compact dense panel padding supported",
            "Launcher compact dense vertical rhythm supported",
            "Launcher rounded scaled metrics supported",
            "Launcher Android compact touch-scale floor supported",
            "Launcher Android-readable warmup screen supported",
            "Launcher Android-readable startup status card supported",
            "Launcher compact dynamic content width supported",
            "Launcher tablet/wide content layout supported",
            "Launcher top-anchored portal content supported",
            "Launcher compact vertical status hero supported",
            "Launcher compact low-profile status card supported",
            "Launcher compact status headline row supported",
            "Launcher compact short status details supported",
            "Launcher compact stacked status headline supported",
            "Launcher viewport-aware compact status headline reflow supported",
            "Launcher compact stable status detail row supported",
            "Launcher compact sticky workflow step strip supported",
            "Launcher compact low-profile workflow step strip supported",
            "Launcher compact low-profile two-column workflow step strip supported",
            "Launcher compact workflow step direct navigation supported",
            "Launcher compact single-row numbered workflow step strip supported",
            "Launcher compact two-column workflow step strip supported",
            "Launcher compact narrow workflow single-row supported",
            "Launcher compact visible workflow step labels supported",
            "Launcher compact workflow step detail labels supported",
            "Launcher compact workflow step number badges supported",
            "Launcher compact workflow unified touch height supported",
            "Launcher compact current-task jump supported",
            "Launcher compact sticky current-task bar supported",
            "Launcher compact low-profile current-task bar supported",
            "Launcher compact dense inline current-task bar supported",
            "Launcher compact current-task shared touch height supported",
            "Launcher compact low-profile stacked current-task bar supported",
            "Launcher compact current-task context labels supported",
            "Launcher compact structured current-task labels supported",
            "Launcher compact current-task short title labels supported",
            "Launcher compact touch-safe sticky header controls supported",
            "Launcher compact grouped sticky task header supported",
            "Launcher compact sticky task toolbar shell supported",
            "Launcher compact inline sticky task header supported",
            "Launcher compact responsive sticky task header supported",
            "Launcher viewport-aware sticky task header reflow supported",
            "Launcher viewport-aware compact task re-anchor supported",
            "Launcher compact dense sticky task header supported",
            "Launcher compact task-jump navigation labels supported",
            "Launcher compact readable detail label font supported",
            "Launcher compact padded scroll anchors supported",
            "Launcher keyboard-focused input scroll supported"
        )
}
