function Add-SteamVersionSelectionLoginPortalEvidenceDocsValidationMatrixCompactActionChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures compact install, login action, cloud-safety, and support action validation evidence" `
        @(
            "Game version dropdown visible/readable",
            "Version/download guidance states local game files are separate from Steam Cloud saves",
            "Ready-state version details repeat that Steam Cloud saves move only through Pull/Push",
            "Play and Sync section appears when actions are available",
            "Pull from Cloud completed",
            "Push to Cloud guarded by confirmation",
            "Game launch completed",
            "Compact launcher-log copy action says Copy Log / Review first",
            "Launcher compact selected-version headline supported",
            "Launcher compact selected-version summary shortcut supported",
            "Launcher compact responsive selected-version summary supported",
            "Launcher compact contextual confirmation labels supported",
            "Launcher compact scroll-safe confirmation dialogs supported",
            "Launcher viewport-aware confirmation dialogs supported",
            "Launcher compact Steam Guard large input supported",
            "Launcher compact Steam Guard action-first layout supported",
            "Launcher compact Steam Guard inline action row supported",
            "Launcher compact responsive Steam Guard action layout supported",
            "Launcher viewport-aware compact Steam Guard action row reflow supported",
            "Launcher compact Steam Guard submit detail label supported",
            "Launcher compact Steam Guard retry guidance supported",
            "Launcher compact Steam Guard bounded helper supported",
            "Launcher compact primary retry action supported",
            "Launcher compact structured retry action labels supported",
            "Launcher compact primary login action first supported",
            "Launcher compact Android login primary CTA supported",
            "Launcher compact Android login detail label supported",
            "Launcher compact Android login helper detail label supported",
            "Launcher compact completed-auth section suppression supported",
            "Launcher touch-first action targets supported",
            "Launcher primary action wording supported",
            "Launcher consistent Start Game CTA supported",
            "Launcher compact launch detail label supported",
            "Launcher branded atmospheric background supported",
            "Launcher branded background explicit RGBA supported",
            "Launcher high-contrast rounded actions supported",
            "Launcher compact header chrome reduction supported",
            "Launcher compact condensed brand header supported",
            "Launcher compact single-line brand header supported",
            "Launcher compact readable brand subtitle supported",
            "Launcher compact section-header subtitle suppression supported",
            "Launcher compact low-profile section headers supported",
            "Launcher compact single-row section headers supported",
            "Launcher compact section-header task cues supported",
            "Launcher compact explicit section-header cues supported",
            "Launcher compact install primary action first supported",
            "Launcher compact install primary detail label supported",
            "Launcher compact download progress hero supported",
            "Launcher compact download progress status label supported",
            "Launcher compact inline install-version controls supported",
            "Launcher compact version details collapsible",
            "Launcher compact structured install-version action labels supported",
            "Launcher compact ready-version summary panel supported",
            "Launcher compact ready-version summary shortcut supported",
            "Launcher compact ready-version headline supported",
            "Launcher compact responsive ready-version summary supported",
            "Launcher compact ready-state priority supported",
            "Launcher compact ready-state cloud options below launch supported",
            "Launcher compact ready-state install-section suppression supported",
            "Launcher compact touch-safe version dropdown supported",
            "Launcher compact touch-safe dropdown popup supported",
            "Launcher compact cloud-safety cue before actions supported",
            "Launcher compact cloud-safety detail label supported",
            "Launcher compact cloud direction labels supported",
            "Launcher compact cloud primary actions row supported",
            "Launcher compact Pull detail label supported",
            "Launcher compact responsive action rows supported",
            "Launcher compact dangerous Push detail labels supported",
            "Launcher compact armed Push warning detail label supported",
            "Launcher compact launcher-log review label supported",
            "Launcher compact cloud options row supported",
            "Launcher compact cloud option detail labels supported",
            "Launcher version-install/cloud-save separation guidance supported"
        )
}
