function Add-SteamVersionSelectionReleaseDocsUserGuideBranchCloudChecks {
    Add-Check `
        "docs\steam-version-selection-user-guide.md" `
        "keeps branch-switch and manual cloud marker evidence visible" `
        @(
            "Branch switch marker filename",
            "Branch switch marker path",
            "Branch switch marker UTC",
            "Branch switch marker UTC parseable",
            "Branch switch previous branch",
            "Branch switch selected branch",
            "Branch switch selected version",
            "Branch switch selected version slot kind",
            "Branch switch selected version slot directory",
            "Branch switch selected branch matches current selected branch",
            "Branch switch selected branch note",
            "Branch switch local backup forced",
            "Branch switch manual Push requires backup storage",
            "Branch switch warning acknowledged",
            "Branch switch non-public warning acknowledged",
            "Branch switch marker has required safety evidence",
            "Branch switch marker has required safety evidence for selected branch",
            "Branch-switch manual Push prerequisites satisfied",
            "Pre-Push local backup evidence count",
            "Pre-Push cloud backup evidence count",
            "Latest pre-Push local backup UTC",
            "Latest pre-Push cloud backup UTC",
            "Pre-Push local backup evidence after branch switch",
            "Pre-Push cloud backup evidence after branch switch",
            "Branch-switch pre-Push backup evidence satisfied",
            "Manual Pull evidence marker filename",
            "last_manual_cloud_push\.txt",
            "last_manual_cloud_push_blocked\.txt",
            "Manual Pull evidence marker filename",
            "Manual Pull evidence marker path",
            "Manual Pull evidence UTC",
            "Manual Pull evidence UTC parseable",
            "Manual Pull evidence selected branch",
            "Manual Pull evidence selected version",
            "Manual Pull evidence selected version slot kind",
            "Manual Pull evidence selected version slot directory",
            "Manual Pull completion flag recorded",
            "Manual Pull evidence is after branch switch",
            "Manual Pull evidence matches selected branch",
            "Manual Pull completed after branch switch",
            "Manual Push evidence marker filename",
            "Manual Push evidence marker path",
            "Manual Push evidence UTC",
            "Latest manual Push evidence outcome",
            "Latest manual Push evidence UTC",
            "Latest manual Push evidence selected branch",
            "Latest manual Push evidence selected version",
            "Latest manual Push evidence selected version slot kind",
            "Latest manual Push evidence selected version slot directory",
            "Latest manual Push evidence reason",
            "Manual Push evidence UTC parseable",
            "Manual Push evidence selected branch",
            "Manual Push evidence selected version",
            "Manual Push evidence selected version slot kind",
            "Manual Push evidence selected version slot directory",
            "Manual Push evidence recorded local backup count",
            "Manual Push evidence recorded cloud backup count",
            "Manual Push evidence recorded latest local backup UTC",
            "Manual Push evidence recorded latest cloud backup UTC",
            "Manual Push completion flag recorded",
            "Manual Push evidence is after branch switch",
            "Manual Push evidence matches selected branch",
            "Manual Push evidence recorded pre-Push backup evidence satisfied",
            "Manual Push completed after branch switch for selected version with backup evidence",
            "Manual Push blocked evidence marker filename",
            "Manual Push blocked evidence marker path",
            "Manual Push blocked evidence UTC",
            "Manual Push blocked evidence UTC parseable",
            "Manual Push blocked evidence selected branch",
            "Manual Push blocked evidence selected version",
            "Manual Push blocked evidence selected version slot kind",
            "Manual Push blocked evidence selected version slot directory",
            "Manual Push blocked evidence matches selected branch",
            "Manual Push blocked evidence reason",
            "Manual Push blocked before upload evidence recorded",
            "Game version cache cleanup marker selected cache preserved where applicable",
            "Pull from Cloud first"
        )
}
