function Add-SteamVersionSelectionLoginPanelNativeAndroidLayoutChecks {
    Add-Check `
        "android\src\com\game\sts2launcher\GodotApp.java" `
        "keeps native Steam credential panel responsive to Android viewport and keyboard changes" `
        @(
            "Show password",
            "Hide password",
            "toggleSteamLoginCredentialPasswordVisibility",
            "TYPE_TEXT_VARIATION_VISIBLE_PASSWORD",
            "boolean wideCredentialLayout = useSteamLoginCredentialWideLayout\(\)",
            "steamLoginCredentialShortHeightLayout",
            "boolean shortHeightCredentialLayout = wideCredentialLayout && useSteamLoginCredentialShortHeightLayout\(\)",
            "useSteamLoginCredentialWideLayout",
            "width > height && width >= dp\(640\)",
            "useSteamLoginCredentialShortHeightLayout",
            "height < dp\(430\)",
            "steamLoginCredentialUsableHeightPixels",
            "getWindow\(\)",
            "getDecorView\(\)",
            "getWindowVisibleDisplayFrame\(visibleFrame\)",
            "visibleWideLayout != steamLoginCredentialWideLayout",
            "visibleShortHeightLayout != steamLoginCredentialShortHeightLayout",
            "shortHeightCredentialLayout == steamLoginCredentialShortHeightLayout",
            "translateSteamLoginCredentialStatusForLayout",
            "steamLoginCredentialDefaultStatusText\(boolean shortHeightLayout\)",
            "steamLoginCredentialShownStatusText\(boolean shortHeightLayout\)",
            "Use Android password suggestions here\. Credentials clear after one Steam handoff\.",
            "Not stored by StS2 Mobile\.",
            "steamLoginCredentialDefaultStatusText",
            "steamLoginCredentialShownStatusText",
            "steamLoginCredentialPanelWidth\(wideCredentialLayout\)",
            "createSteamLoginCredentialInputRow\(wideCredentialLayout\)",
            "credentialFieldLayoutParams\(wideCredentialLayout\)",
            "credentialInlineActionLayoutParams\(wideCredentialLayout, 4\)",
            "credentialInlineActionLayoutParams\(wideCredentialLayout, 6\)",
            "credentialSubmitButtonLayoutParams\(wideCredentialLayout\)",
            "credentialCancelButtonLayoutParams\(wideCredentialLayout\)",
            "new LinearLayout\.LayoutParams\(dp\(178\), LinearLayout\.LayoutParams\.WRAP_CONTENT\)",
            "onConfigurationChanged",
            "Configuration newConfig",
            "reflowSteamLoginCredentialPanelForCurrentWindow",
            "wideCredentialLayout == steamLoginCredentialWideLayout",
            "onBackPressed",
            "dispatchKeyEvent",
            "KEYCODE_BACK",
            "dismissSteamLoginCredentialPanelFromBack",
            "isSteamLoginCredentialPanelVisible",
            "public boolean isSteamLoginCredentialPanelVisible",
            "hideKeyboardForSteamLoginCredentialPanel",
            "focusedView\.clearFocus\(\)",
            "styleSteamLoginCredentialButton",
            "field\.setMinHeight\(dp\(56\)\)",
            "field\.setPadding\(dp\(14\), 0, dp\(14\), 0\)",
            "field\.setBackground\(background\)",
            "button\.setMinHeight\(dp\(primary \? 60 : 56\)\)",
            "ScrollView",
            "steamLoginCredentialScrollView",
            "updateSteamLoginCredentialKeyboardInsets",
            "scheduleSteamLoginCredentialFocusScroll",
            "Gravity\.TOP \| Gravity\.CENTER_HORIZONTAL",
            "scroll\.setClipToPadding\(false\)",
            "buttons\.setOrientation\(wideCredentialLayout \? LinearLayout\.HORIZONTAL : LinearLayout\.VERTICAL\)",
            "buttonLayoutParams"
        )
}
