function Add-SteamVersionSelectionReleaseStatusDocsReleaseNoteUxChecks {
    Add-Check `
        "docs\steam-version-selection-release-note-snippet.md" `
        "describes the current polished launcher portal UX alongside version-selection limitations" `
        @(
            "cleaner status-led portal",
            "titled action sections",
            "hidden Help & Reports drawer",
            "plain-language help-report and launcher-log status copy",
            "readable bounded compact diagnostics log viewport",
            "stronger branded header",
            "single-line compact brand",
            "readable compact brand subtitle",
            "plain-language readable compact brand subtitle",
            "responsive compact status headline row with stacked narrow-screen fallback",
            "viewport-aware compact status headline reflow after rotation or keyboard viewport changes",
            "stable one-line compact status detail row with short mobile copy, tap-to-expand full status, and a visible Details/Hide cue",
            "Android compact touch-scale floor for small-device readability",
            "Android-readable shader warmup/loading",
            "Android-readable post-launch startup status card",
            "responsive touch-safe compact sticky task header in a low-profile toolbar shell with a subdued inline current-task button and two-line workflow step cells using a shared 62px touch height",
            "contextual current-task detail labels",
            "readable stacked current-task row",
            "two-line single-row compact workflow strip on narrow screens",
            "viewport-aware sticky task header reflow after rotation or keyboard viewport changes",
            "viewport-aware compact task re-anchoring after rotation or keyboard viewport changes",
            "readable step-number badges",
            "Sign in with Steam / Android login",
            "Verify Code / Submit once",
            "Start Game / Ready version",
            "structured Play/Sync title/detail action labels",
            "Save Check / Get saves first",
            "Saves for / Get Steam saves before upload / Upload can overwrite Steam",
            "Get Steam Saves / Download to Android",
            "structured locked-Push title/detail labels",
            "Upload to Steam / Overwrite cloud",
            "Confirm Upload / Overwrite cloud",
            "Steam Cloud overwrite / Confirm only after Pull/local saves are verified",
            "responsive compact action rows",
            "responsive selected-version install summary",
            "touch-safe compact version dropdown popups",
            "inline compact install-version dropdown/refresh controls with structured title/detail labels",
            "version details with structured compact version-file drawer labels",
            "responsive ready-version summary",
            "compact ready-state priority that keeps the ready summary, Save Check shortcut, and Get-saves-first cloud controls before Start Game while moving version management below the primary launch path",
            "compact ready-state cloud options stay below Start Game as an optional save-settings drawer after Get-saves-first cloud controls",
            "large compact Android sign-in CTA with readable two-line",
            "responsive compact Steam Guard code controls",
            "viewport-aware compact Steam Guard code/action row reflow after rotation or keyboard viewport changes",
            "compact Steam Guard bounded two-line helper labels",
            "primary structured compact retry recovery",
            "structured compact startup recovery actions",
            "compact user-facing support tool labels such as Safe Start / Cloud off, Check Files / Updates, Game Versions / Refresh list, Repair Files / Rebuild game, Free Space / Old versions, Help Report / Share details, Last Problem / Open details, and Copy Log / Review first",
            "short-height copy on cramped landscape screens",
            "short-height copy reflow when the landscape height class changes",
            "keyboard-reduced usable height",
            "scroll-safe compact confirmations",
            "bounded compact quick-start guide panel",
            "collapsible quick-start guidance with structured compact Quick Start / Get saves first title/detail labels and bounded guide row cards that suppress during active compact task screens",
            "dense compact drawer toggles",
            "structured compact title/detail labels",
            "native fallback recovery screens that keep verbose diagnostics collapsed until requested and split actions into responsive rows on narrow landscape screens",
            "dense compact vertical rhythm",
            "single-row compact section headers with explicit short task cues such as Steam account, Current code, Local files, and Play safely",
            "mobile-first compact panel sizing with dense compact shell padding",
            "Steam sign-in/Steam Guard/install/play-sync sections",
            "Android/Samsung/password-manager suggestion behavior"
        )
}
