function Add-SteamVersionSelectionDiagnosticsReportingCachedVersionChecks {
    Add-Check `
        "src\STS2Mobile\Launcher\LauncherDiagnostics.ReportCachedGameVersions.cs" `
        "reports cached game-version cleanup and redownload evidence" `
        @(
            "Current selected branch for version marker comparison",
            "Game version cache cleanup marker filename",
            "Game version cache cleanup marker path",
            "Game version cache cleanup marker present",
            "Game version cache cleanup marker UTC",
            "Game version cache cleanup marker UTC parseable",
            "Game version cache cleanup marker selected branch",
            "Game version cache cleanup marker matches selected branch",
            "Game version cache cleanup marker selected version",
            "Game version cache cleanup marker selected version slot kind",
            "Game version cache cleanup marker selected version slot directory",
            "Game version cache cleanup marker game_versions present",
            "Game version cache cleanup marker runtime_packs present",
            "Game version cache cleanup marker selected runtime pack directory",
            "Game version cache cleanup marker selected runtime pack present before cleanup",
            "Game version cache cleanup marker removed count",
            "Game version cache cleanup marker removed runtime pack count",
            "Game version cache cleanup marker selected cache preserved where applicable",
            "Game version cache cleanup marker selected runtime pack preserved where applicable",
            "Game version redownload marker filename",
            "Game version redownload marker path",
            "Game version redownload marker present",
            "Game version redownload marker UTC parseable",
            "Game version redownload marker selected branch",
            "Game version redownload marker matches selected branch",
            "Game version redownload marker selected version",
            "Game version redownload marker selected version slot kind",
            "Game version redownload marker selected version slot directory",
            "Game version redownload marker game directory existed before delete",
            "Game version redownload marker game directory exists after delete",
            "Game version redownload marker download state directory existed before delete",
            "Game version redownload marker download state directory exists after delete",
            "Game version redownload marker selected directories cleared",
            "branchMarkerExpectedInstallSlotKind",
            "branchMarkerExpectedInstallSlotDirectory",
            "branchMarkerMatchingInstallSlotProvenance",
            "branchMarkerDepotsMatchingPublic",
            "branchMarkerDepotsDifferingFromPublic",
            "branchMarkerDepotsInheritedFromPublic",
            "branchMarkerDepotsMissingSelectedManifest",
            "branchMarkerReady",
            "Cached non-public game versions"
        )
}
