function Add-SteamVersionSelectionBranchEvidenceSelectorChecks {
    Add-Check `
        "docs\steam-version-selection-evidence-template.md" `
        "captures selector, branch-switch, and readiness evidence" `
        @(
            "Selector mode",
            "Branch discovery",
            "Android credential provider model",
            "Launcher stores Steam password for credential providers",
            "SteamKit debug logs opt-in status",
            "disabled by default",
            "Steam branch dropdown option metadata",
            "Static guardrails",
            "steam-version-selection-release-readiness\.md",
            "audit-steam-version-selection\.ps1",
            "audit-steam-branch-guidance-parity\.ps1",
            "blocked states",
            "Selector helper text shows the active install slot",
            "selected game version note",
            "selected game version slot kind",
            "Native pre-routing logs selected branch",
            "selected branch note",
            "branch switch marker filename",
            "Branch switch marker records",
            "parseable UTC",
            "required-evidence status",
            "Branch switch previous branch",
            "Branch switch selected branch",
            "Branch switch selected version",
            "Branch switch selected version slot kind",
            "Branch switch selected version slot directory",
            "Branch switch selected branch matches current selected branch",
            "Branch switch selected branch note",
            "Branch switch local backup forced",
            "Branch switch manual Push requires backup storage",
            "Branch switch warning acknowledged",
            "Branch switch non-public warning acknowledged",
            "Branch switch marker has required safety evidence",
            "Branch switch marker has required safety evidence for selected branch",
            "Branch-switch manual Push prerequisites satisfied",
            "Pre-Push local backup evidence count",
            "Pre-Push cloud backup evidence count",
            "Latest pre-Push local backup UTC",
            "Latest pre-Push cloud backup UTC",
            "Pre-Push local backup evidence after branch switch",
            "Pre-Push cloud backup evidence after branch switch",
            "Branch-switch pre-Push backup evidence satisfied",
            "Steam beta password",
            "save compatibility"
        )
}
