function Add-SteamVersionSelectionPortalUxNarrativeChecks {
    Add-Check `
        "src\STS2Mobile\Launcher\LauncherPortalUxSupport.cs" `
        "keeps secret-safe portal UX narrative and validation boundary text" `
        @(
            "Status-led launcher portal",
            "compact plain-language status copy for sign-in, ownership check, install-needed, and ready-to-play states",
            "Steam sign-in",
            "Steam Guard",
            "game install",
            "play/sync",
            "low-profile status card",
            "stacked phase and next-action labels",
            "stable one-line non-attention detail row",
            "compact touch-safe responsive numbered workflow step strip with visible two-line step labels, separate readable number badges, and a unified 62px touch height",
            "stays one dense row even on narrow compact viewports",
            "tappable compact workflow steps that directly navigate to visible or fallback task sections",
            "subdued inline current-task jump button and two-line workflow cells that share the 62px compact touch height in a low-profile toolbar shell around the touch-safe sticky compact task header",
            "reflows between inline and stacked layouts after Android rotation or keyboard viewport changes",
            "compact current-task jump button",
            "touch-safe sticky compact task bar",
            "structured two-line app-like task title/detail labels",
            "contextual task detail labels",
            "compact touch-safe confirmation dialogs with wider scroll-safe warning text, contextual confirm/cancel labels, and current-viewport sizing after rotation or keyboard viewport changes",
            "compact Android sign-in primary action before helper copy",
            "compact Android sign-in CTA promoted to a large primary action with Sign in with Steam / Android login detail labels before the readable two-line password-manager safety helper",
            "larger compact Steam Guard code entry and Verify Code controls before helper copy, inline where width allows and stacked full-width on narrow compact viewports",
            "compact Steam Guard submit detail labels that keep Verify Code / Submit once action-first",
            "compact Steam Guard bounded two-line helper labels that keep one-shot/no-storage and newest-code retry guidance below the action row",
            "compact failure recovery promoted to a primary Try Again / Restart task action while cloud controls remain hidden",
            "compact completed-auth section suppression",
            "consistent Start Game primary CTA with compact Start Game / Ready version detail labels",
            "Android compact touch-scale floor for small-device readability",
            "Android-readable shader warmup/loading screen",
            "Android-readable startup status card",
            "verbose native fallback diagnostics collapsed until requested",
            "responsive recovery rows on narrow landscape screens",
            "bounded compact quick-start guide panel",
            "collapsible compact quick-start guidance with structured Quick Start / Get saves first title/detail labels",
            "compact active-task safe-flow suppression after setup",
            "compact install step ordering with selected-version summary and a large Download Version / Local files only primary action before optional version details",
            "compact install primary action detail labels for download, redownload, retry, and disabled downloading states",
            "compact install-version drawer controls with structured title/detail labels that keep the version dropdown and refresh action inline where width allows and stack on narrow compact viewports",
            "collapsible compact version details with structured version-file drawer labels and bounded two-line Files for / Play version helper labels",
            "compact download progress promoted directly under the disabled Downloading primary action with a stable two-line Downloading selected version status label",
            "compact readable selected-version and ready-version summary cards",
            "compact responsive selected-version summary that stays explicit about Cloud unchanged/local-file scope and opens the version drawer from a touch-safe Change shortcut",
            "compact ready-version summary",
            "compact ready-version summary panel",
            "compact responsive ready-version summary with Save Check shortcut opens Save Check from a touch-safe Upload-locked cue without unlocking Push",
            "CompactReadyStatePriorityDescription",
            "compact ready-state priority that keeps the ready summary, Save Check shortcut, and Get-saves-first cloud controls before Start Game while moving version management below the primary launch path",
            "CompactReadyStateCloudOptionsBelowLaunchDescription",
            "compact ready-state cloud options stay below Start Game as an optional save-settings drawer after Get-saves-first cloud controls",
            "compact Play/Sync drawer detail labels rendered as structured title/detail action labels",
            "CompactPlainLanguagePlaySyncLabelsDescription",
            "compact Play/Sync uses plain-language save copy such as Get Steam Saves, Upload Locked, Save Check, and Fixes & Help while keeping upload collapsed and explicit",
            "compact user-facing support tool labels such as Safe Start / Cloud off, Check Files / Updates, Game Versions / Refresh list, Repair Files / Rebuild game, Free Space / Old versions, Help Report / Share details, Last Problem / Open details, and Copy Log / Review first",
            "compact responsive action rows that keep save get/upload actions, save settings, and support tools side-by-side where space allows and stack them into full-width controls on narrow compact viewports",
            "compact ready-state install-section suppression",
            "touch-safe compact version dropdowns with larger opened popup row spacing/padding",
            "collapsible compact Save Check / Get saves first cloud-safety drawer labels shown before get/upload actions with a stable two-line Saves for / Get Steam saves before upload / Upload can overwrite Steam detail label",
            "compact cloud action labels that name Android as the Pull destination and Steam as the Push destination",
            "compact Pull detail labels that keep Get Steam Saves / Download to Android direction-explicit",
            "compact locked Push toggle labels that stay structured as Upload Locked / Review first and Hide Upload / Keep locked",
            "compact dangerous Push detail labels that keep Upload to Steam / Overwrite cloud and Confirm Upload / Overwrite cloud direction-explicit after unlock",
            "compact armed Push overwrite warning rendered as a stable Steam Cloud overwrite / Confirm only after Pull/local saves are verified label",
            "compact drawer state reset",
            "compact touch-safe dense drawer toggles before expanded drawer details",
            "compact drawer collapse after version selection",
            "compact state-transition active-section scroll",
            "compact primary-action scroll anchors",
            "padded compact scroll anchors that keep jumped-to task sections below the sticky header",
            "viewport-aware compact task re-anchoring after rotation or keyboard viewport changes",
            "rounded shared metric scaling",
            "compact bottom scroll breathing room",
            "compact low-profile attribution footer",
            "compact scroll-hosted Help & Reports drawer with structured touch-safe drawer title/detail labels, plain-language help-report and launcher-log status copy, a readable bounded compact diagnostics log viewport, and viewport-aware diagnostics log resizing",
            "compact dense vertical rhythm with single-row section headers and explicit short task cues such as Steam account, Current code, Local files, and Play safely",
            "mobile-first compact panel sizing with dense compact shell padding",
            "viewport-aware keyboard offset refresh",
            "keyboard-focused input scrolling so managed Steam Guard and fallback credential fields stay reachable above the soft keyboard",
            "compact ready-state safe-flow suppression",
            "scroll-safe startup recovery controls",
            "hidden diagnostics drawer with automatic opening for explicit diagnostics actions",
            "styled native fallback recovery actions",
            "ARM64 visual validation"
        )
}
