function Add-SteamVersionSelectionLoginValidationDocsCompactActionChecks {
    Add-Check `
        "docs\android-steam-login-validation.md" `
        "keeps compact install, ready-state, cloud, and support action documentation checks focused" `
        @(
            "Launcher touch-first action targets supported:",
            "Launcher primary action wording supported:",
            "Launcher consistent Start Game CTA supported:",
            "Launcher compact launch detail label supported:",
            "Launcher branded atmospheric background supported:",
            "Launcher branded background explicit RGBA supported:",
            "Launcher high-contrast rounded actions supported:",
            "Launcher compact header chrome reduction supported:",
            "Launcher compact condensed brand header supported:",
            "Launcher compact single-line brand header supported:",
            "Launcher compact readable brand subtitle supported:",
            "The compact brand subtitle remains readable at phone scale and uses plain app copy instead of pipe-separated command-line-style labels.",
            "Launcher compact section-header subtitle suppression supported:",
            "Launcher compact low-profile section headers supported:",
            "Launcher compact single-row section headers supported:",
            "Launcher compact section-header task cues supported:",
            "Launcher compact readable section-header cues supported:",
            "Launcher compact explicit section-header cues supported:",
            "Launcher compact install primary detail label supported:",
            "Launcher compact download progress hero supported:",
            "Launcher compact download progress status label supported:",
            "Launcher compact readable download progress bar supported:",
            "Launcher compact inline install-version controls supported:",
            "Launcher compact version details collapsible:",
            "Launcher compact version drawer bounded help label supported:",
            "Launcher compact structured install-version action labels supported:",
            "Launcher compact version summary cards supported:",
            "Launcher compact selected-version summary shortcut supported:",
            "Launcher compact selected-version headline supported:",
            "Launcher compact responsive selected-version summary supported:",
            "Launcher compact ready-version summary panel supported:",
            "Launcher compact ready-version summary shortcut supported:",
            "Launcher compact ready-version headline supported:",
            "Launcher compact responsive ready-version summary supported:",
            "Launcher compact structured Play/Sync action labels supported:",
            "Launcher compact ready-state install-section suppression supported:",
            "Launcher compact touch-safe version dropdown supported:",
            "Launcher compact touch-safe dropdown popup supported:",
            "Launcher compact cloud-safety guidance collapsible:",
            "Launcher compact cloud-safety detail label supported:",
            "Launcher compact cloud options collapsible:",
            "Launcher primary cloud actions before cloud options:",
            "Launcher compact cloud option detail labels supported:",
            "Launcher safer Pull-before-Push cloud ordering supported:",
            "Launcher compact cloud direction labels supported:",
            "Launcher compact cloud primary actions row supported:",
            "Launcher compact Pull detail label supported:",
            "Launcher compact responsive action rows supported:",
            "Launcher compact dangerous Push detail labels supported:",
            "Launcher compact armed Push warning detail label supported:",
            "Launcher manual Push armed overwrite warning supported:",
            "Launcher compact cloud options row supported:",
            "Launcher version-install/cloud-save separation guidance supported:",
            "Launcher Help & Reports drawer hidden by default:",
            "Launcher Help & Reports drawer auto-opens for diagnostics actions:",
            "Compact diagnostics toggle renders .*Help & Reports.*Private until opened.*structured title/detail labels",
            "Launcher compact low-profile drawer toggles supported:",
            "Launcher compact dense drawer toggle height supported:",
            "Launcher compact support tools grid supported:",
            "Launcher compact launcher-log review label supported:",
            "Launcher plain-language help report copy supported:",
            "Launcher startup recovery structured compact actions supported:",
            "Launcher compact low-profile diagnostics toggle supported:",
            "Launcher compact diagnostics toggle detail labels supported:",
            "Launcher compact structured diagnostics toggle labels supported:"
        )
}
