function Add-SteamVersionSelectionLoginPortalEvidenceDocsCompactWorkflowChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures compact launcher workflow, layout, status, and section evidence" `
        @(
            "Quick-start guide visible",
            "On compact phone layout, quick-start guidance starts collapsed",
            "Compact quick-start toggle says Quick Start / Get saves first and is touch-safe",
            "Compact quick-start toggle renders Quick Start / Get saves first as structured title/detail labels",
            "Compact expanded quick-start guide stays bounded and shows Sign in, Get files, Get saves, Play, and Upload locked rows",
            "Compact expanded quick-start guide renders each step inside a bounded row card",
            "Compact active task screens suppress the quick-start drawer so primary controls stay higher",
            "Quick-start guidance expands/collapses without hiding the primary task",
            "Compact phone layout uses most of the usable screen height",
            "Compact phone layout avoids excessive internal panel margins",
            "Compact phone shell uses dense panel padding",
            "Compact phone layout uses dense vertical spacing between repeated launcher regions",
            "Compact phone layout uses dynamic content width instead of a narrow fixed column",
            "Tablet/wide layout avoids a narrow fixed inner column",
            "Android warmup/loading screen uses a mobile-width compact panel with readable styled progress",
            "Android post-launch startup status uses a framed mobile-width readable card",
            "Native fallback verbose diagnostics collapsed until requested",
            "Startup recovery compact actions render Restart App / Open launcher, Safe Start / Cloud off, Help Report / Share details, Copy Log / Review first, and Hide Help / Keep waiting",
            "Native fallback recovery actions split into responsive rows on narrow landscape screens",
            "Portal task flow is top anchored rather than vertically stranded",
            "Compact phone status appears as a readable vertical next-step card",
            "Compact phone status card is low-profile but still readable",
            "Compact status card uses an inline phase and next-action headline where width allows",
            "Compact status card stacks phase and next action without squeezing either label on narrow compact screens",
            "Compact status uses short mobile detail copy and expands full raw status when tapped",
            "Compact status exposes a visible Details / Hide cue in a touch-safe row",
            "Launcher compact touch-safe status detail button supported",
            "Launcher compact status detail cue supported",
            "Compact responsive numbered workflow step strip remains visible while scrolling",
            "Compact workflow step strip stays in one dense row on narrow compact viewports",
            "Compact workflow step strip uses unified 62px touch-height cells on narrow compact viewports",
            "Compact workflow step strip shows two-line visible labels, not only numbers/tooltips",
            "Sign in / Account, Verify / Steam Guard, Files / Game files, and Play / Saves safe",
            "Compact workflow step strip separates step numbers into small badges next to readable labels",
            "Launcher compact workflow step detail labels supported",
            "Launcher compact workflow unified touch height supported",
            "Tapping compact workflow step labels scrolls directly to visible matching task sections or the current safe fallback task",
            "Compact workflow step strip uses the same larger touch height as compact task actions",
            "Compact current-task bar remains reachable while scrolling",
            "Compact current-task bar uses app-like task title wording",
            "Compact current-task bar uses contextual task detail labels",
            "Compact current-task bar renders task/context labels as structured title/detail labels",
            "Compact current-task bar is touch-safe but still compact",
            "Compact inline current-task bar is dense while remaining touch-safe",
            "Compact current-task bar and workflow strip share a tight sticky header",
            "Compact current-task bar and workflow strip share one inline sticky row when width allows",
            "Compact stacked current-task row is low-profile on narrow compact viewports",
            "Compact sticky task header is grouped inside a low-profile toolbar shell",
            "Compact sticky task header stacks on narrow compact viewports",
            "Compact sticky task header keeps the narrow workflow row dense enough to leave action content visible",
            "Compact sticky task header reflows between inline and stacked layouts after rotation or keyboard viewport changes",
            "Compact active task remains re-anchored after rotation or keyboard viewport changes"
        )
}
