function Add-SteamVersionSelectionLoginPortalEvidenceDocsValidationMatrixNativeCredentialChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures ARM64 native credential and Steam Guard validation evidence" `
        @(
            "Username keyboard next action focuses password",
            "Next button focuses password and requests password suggestions",
            "Password keyboard done action attempts submit",
            "Password-manager suggestions",
            "Samsung Pass",
            "Google Password Manager",
            "Steam Guard prompt visible",
            "Steam Guard field accepts alphanumeric input",
            "Compact Steam Guard code field and Verify button are large enough to tap comfortably",
            "Compact Steam Guard shows code field and Verify Code before helper copy",
            "Compact Steam Guard code field and Verify Code share one touch-safe action row when width allows",
            "Compact Steam Guard code field and Verify Code stack full-width on narrow compact viewports",
            "Compact Steam Guard submit action says Verify Code / Submit once",
            "Compact Steam Guard retry keeps the rejected-code title short and moves latest-code guidance into the helper below the code controls",
            "Compact retry/failure recovery button is primary and uses Try Again / Restart task labels",
            "Wrong password produces recoverable failure",
            "Failed-login status gives clear retry guidance",
            "Failed-login status states Steam passwords are not stored",
            "Connection/session failure gives connection-specific recovery guidance",
            "Steam Guard section states code is submitted once and never stored",
            "Wrong Steam Guard code asks for the latest Steam Guard code",
            "Successful login returns to launcher",
            "Native credential panel inline status configured",
            "Native credential panel keyboard-safe layout configured",
            "Native credential panel IME inset scroll supported",
            "Native credential panel touch-target layout configured",
            "Native credential panel requests both Autofill fields",
            "Native credential panel focus Autofill requests supported",
            "Native credential panel task-led buttons supported",
            "Native credential panel responsive action rows supported",
            "Native credential panel orientation reflow supported",
            "Native credential panel short-height copy supported",
            "Native credential panel short-height reflow supported",
            "Native credential panel IME height reflow supported",
            "Native credential panel password visibility toggle supported",
            "Native credential panel password-focus button supported",
            "Native credential panel Back dismiss supported",
            "Native credential panel dismiss retry supported",
            "Native credential panel dismiss hides keyboard",
            "Native credential panel suppresses pre-auth save prompt",
            "Steam Guard one-shot code guidance supported",
            "Failed-login retry guidance supported",
            "Context-specific login recovery guidance supported"
        )
}
