function Add-SteamVersionSelectionLoginPortalEvidenceDocsInstallCloudChecks {
    Add-Check `
        "docs\android-login-portal-evidence-template.md" `
        "captures compact install, launch, cloud safety, diagnostics, and recovery evidence" `
        @(
            "Compact Game Install selected-version summary is a readable touch-safe card with Cloud unchanged cue and Change / Change version shortcut",
            "Compact Game Install selected-version summary shortcut opens the version drawer without changing branches or cloud saves",
            "Compact install-version dropdown and refresh controls share one row when width allows",
            "Compact version drawer controls render Change Version / Local files only and Refresh Versions / Update branch list as structured title/detail labels",
            "Compact expanded version helper says Files for / Play version with Default files or Separate files and short branch status",
            "Status card shows a clear guided next action for the current state",
            "Failure/blocked/crash statuses show attention/fix guidance before normal install/cloud/launch guidance",
            "Primary actions use clear task wording, for example sign in/start game/verify code",
            "Primary launch action consistently says Start Game",
            "Primary and secondary actions are large enough to tap comfortably",
            "Launcher background has visible branded atmosphere without reducing readability",
            "Buttons use high-contrast rounded action styling",
            "Compact phone header uses shortened subtitle/chrome",
            "Compact phone brand header is a single low-profile row",
            "Compact phone brand subtitle remains readable at phone scale",
            "Compact phone brand subtitle uses plain app copy instead of pipe-separated labels",
            "Compact phone header leaves more first-action area visible",
            "Compact phone section headers avoid repeated subtitle blocks",
            "Compact phone section headers stay compact and leave controls visible",
            "Compact phone section headers keep title and readable task cue in one dense row without clipping the title",
            "Compact phone section headers use explicit short cues Steam account, Current code, Local files, and Play safely instead of clipped desktop subtitles",
            "Compact Game Install shows selected version and Download before optional version details",
            "Compact version dropdown is large enough to read and tap when expanded",
            "Opened compact game-version dropdown popup rows have larger spacing/padding and are touch-safe",
            "Compact phone version details start collapsed",
            "Version details expand/collapse without changing selected version",
            "Compact download progress appears directly below the disabled DOWNLOADING primary action",
            "Compact download progress uses a taller styled percentage bar",
            "Compact optional drawer toggles are low-profile but still tappable",
            "Compact optional drawer toggles use dense touch-safe height",
            "Compact optional drawer toggles are shorter than primary action buttons",
            "Compact Play/Sync action buttons render title/detail labels as structured two-line controls",
            "Compact launch CTA says Start Game / Ready version",
            "Compact recovery/tools actions use a two-column support grid when width allows",
            "Compact recovery/tools actions stack full-width on narrow compact viewports",
            "Compact phone cloud safety starts collapsed",
            "Compact collapsed cloud-safety drawer reads Save Check / Get saves first so it does not look like the Get Steam Saves action",
            "Compact cloud-safety cue appears before Pull/Push controls",
            "Compact expanded cloud-safety detail says Saves for and Get Steam saves before upload / Upload can overwrite Steam",
            "Cloud safety expands/collapses while preserving Pull/Push controls",
            "Compact phone cloud options start collapsed",
            "Cloud options expand/collapse while preserving Pull/Push controls",
            "Compact Save Backup and Cloud Sync options use Local safety and Steam saves detail labels and share one low-profile row when width allows",
            "Compact Save Backup and Cloud Sync options stack full-width on narrow compact viewports",
            "Pull/Push controls appear before lower-frequency cloud options",
            "Pull from Cloud appears before Push to Cloud",
            "Compact cloud labels name Pull as Android-directed and Push as Steam-directed",
            "Compact Pull action says Get Steam Saves / Download to Android",
            "Compact locked Push toggle renders Upload Locked / Review first and Hide Upload / Keep locked as structured title/detail labels",
            "Compact unlocked Push actions say Upload to Steam / Overwrite cloud and Confirm Upload / Overwrite cloud",
            "Compact armed Push warning says Steam Cloud overwrite / Confirm only after Pull/local saves are verified",
            "Compact Get Steam Saves and locked Steam upload share one two-button row when width allows",
            "Compact Get Steam Saves and locked Steam upload stack with Get Steam Saves first on narrow compact viewports",
            "Armed Push state shows overwrite warning before final confirmation",
            "Branch, redownload, cache, and final Push confirmations use contextual confirm/cancel labels instead of generic OK/Cancel buttons",
            "Long compact confirmation warnings are scroll-safe and keep confirm/cancel buttons reachable",
            "Confirmation dialogs use the current visible viewport after rotation or keyboard-driven viewport changes",
            "Focused managed Steam Guard/fallback input stays visible above the Android soft keyboard",
            "Compact optional drawer toggles remain tappable without taking full primary-action height.",
            "Compact optional drawer toggles use a dense touch-safe height instead of the older tiny drawer rows.",
            "Compact drawer toggles and dense workflow controls share the same touch-safe compact height:",
            "Compact optional drawer toggles are visibly shorter than primary action buttons while still tappable.",
            "Help & Reports drawer hidden by default",
            "Compact diagnostics toggle uses a touch-safe two-line detail label",
            "Compact diagnostics toggle renders title/detail labels as structured controls",
            "Compact diagnostics is inside the scroll body rather than fixed root chrome",
            "Raw startup fallback failure text hidden from portal",
            "The compact workflow strip shows visible step labels such as Sign in / Account, Verify / Steam Guard, Files / Game files, and Play / Saves safe; it does not rely on hover-only tooltips",
            "The compact workflow strip is touch-safe enough for Android while keeping two-line step labels readable",
            "The compact game-version dropdown is large enough to read and tap when the version drawer is expanded",
            "Opening the compact game-version dropdown shows larger touch-safe popup row spacing and horizontal padding",
            "Compact Play and Sync ready-version summary is a readable touch-safe card with Save Check and Upload locked cues",
            "Compact Play and Sync ready-version summary shortcut opens Save Check without unlocking Push",
            "Compact Play and Sync keeps the ready summary, Save Check shortcut, Get-saves-first cloud controls, and Start Game before version management",
            "Compact Play and Sync keeps save backup and cloud sync options below Start Game as optional controls"
        )
}
