function Add-SteamVersionSelectionLoginValidationDocsChecks {
    Add-Check `
        "docs\android-steam-login-validation.md" `
        "defines Android Steam login validation proof contract" `
        @(
            "android-login-portal-evidence-template\.md",
            "integrated in-app native Steam credential panel",
            "real Android username and password fields",
            "no user-facing native credential handoff popup",
            "does not store or inject Steam passwords",
            "real `EditText` fields",
            "Android Autofill hints",
            "Steam web-domain metadata",
            "launcher portal uses explicit status and titled state sections",
            "Diagnostics are hidden behind the Help & Reports drawer",
            "Android warmup/loading uses a mobile-width compact panel with readable styled percentage progress.",
            "Android post-launch startup status uses a framed mobile-width readable card after the launcher closes.",
            "Native fallback keeps verbose diagnostics collapsed until explicitly requested",
            "Native fallback recovery actions split into two touch-friendly rows on narrow landscape screens.",
            "Startup recovery compact actions render as structured user-facing controls: .*Restart App.*Open launcher.*Safe Start.*Cloud off.*Help Report.*Share details.*Copy Log.*Review first.*Hide Help.*Keep waiting",
            "The compact diagnostics toggle uses a touch-safe two-line detail label without exposing diagnostics by default.",
            "Compact diagnostics lives inside the scroll body rather than consuming fixed phone viewport chrome, and explicit diagnostics actions scroll to it.",
            "The compact status card stays readable while using low-profile spacing so more current task content remains visible.",
            "The compact status card stacks the phase chip and guided next action so neither is squeezed on narrow screens.",
            "Compact status details keep normal progress text to one stable line while attention/failure guidance can expand.",
            "Compact status uses short mobile detail copy and expands full raw status when tapped.",
            "Compact status exposes a visible `Details` / `Hide` cue in a touch-safe row.",
            "Compact sign-in status says `Sign in with Steam to continue` instead of exposing the raw credential prompt.",
            "Compact download-needed status says `Download this game version to play` and the next action reads `Install Game`.",
            "Compact ready status says `Ready to play this version` and the next action reads `Start Game`.",
            "Compact quick-start guidance starts collapsed behind a touch-safe two-line toggle that says `Quick Start` and `Get saves first`.",
            "Compact quick-start toggle renders Quick Start / Get saves first as structured title/detail labels",
            "Compact expanded quick-start guide renders each step inside a bounded row card.",
            "Compact sign-in, Steam Guard, and download task screens suppress the quick-start drawer so the current primary controls stay higher in the viewport.",
            "The compact brand subtitle remains readable at phone scale and uses plain app copy instead of pipe-separated command-line-style labels.",
            "The compact workflow strip stays in one dense row on narrow compact viewports instead of taking a second fixed header row.",
            "Tapping compact workflow step labels scrolls directly to the visible matching task section or the current safe fallback task.",
            "Compact recovery/tools actions use a two-column support grid when width allows and full-width stacked tools on narrow compact viewports.",
            "Compact Play and Sync shows the ready version, Save Check guidance, and Upload-locked state in a readable touch-safe summary card that opens Save Check without unlocking Push.",
            "Compact ready state prioritizes the ready summary, Save Check shortcut, Get-saves-first cloud controls, and Start Game before version management.",
            "Compact ready state keeps save backup and cloud sync options below Start Game as optional controls.",
            "Compact Pull action renders .*Get Steam Saves / Download to Android.* as a structured title/detail label",
            "Compact locked upload toggle renders Upload Locked / Review first and Hide Upload / Keep locked as structured title/detail labels:",
            "Compact unlocked Push actions render .*Upload to Steam / Overwrite cloud.* and .*Confirm Upload / Overwrite cloud.* as structured title/detail labels after the upload overwrite drawer is explicitly opened",
            "Compact armed Push warning says Steam Cloud overwrite / Confirm only after Pull/local saves are verified",
            "Compact Get Steam Saves and locked Steam upload share one two-button row when width allows and stack with Get Steam Saves first on narrow compact viewports.",
            "Compact Save Backup and Cloud Sync options use Local safety and Steam saves detail labels, share one low-profile row when width allows, and stack full-width on narrow compact viewports.",
            "Compact Android sign-in shows .*Sign in with Steam.* before password-manager helper copy",
            "Compact Android sign-in CTA renders .*Sign in with Steam / Android login.* as a structured title/detail label",
            "Compact Android sign-in uses a large primary .*Sign in with Steam.* CTA and a readable two-line password-manager safety helper",
            "Compact Steam Guard submit action renders .*Verify Code / Submit once.* as a structured title/detail label",
            "Compact Steam Guard retry keeps the rejected-code title short and moves latest-code guidance into the helper below the code controls",
            "Compact retry/failure state promotes .*Try Again.*Restart task.* primary recovery action while support tools remain secondary",
            "Compact launcher-log copy keeps the short .*Copy Log.* label but uses .*Review first.* detail text before copying diagnostics",
            "The compact current-task bar stays reachable, uses app-like task title wording, and is touch-safe without wasting vertical space",
            "The compact current-task bar uses short title labels such as .*Sign in.*, .*Verify.*, .*Files.*, and .*Play.* without a status prefix",
            "The compact current-task bar uses contextual detail labels such as .*Steam account.*, .*Steam Guard code.*, .*Download version.*, and .*Play and saves.*.",
            "The compact current-task bar renders task names and contextual details as structured title/detail labels",
            "The compact inline current-task bar uses dense height while staying touch-safe, so the persistent header does not crowd active controls.",
            "The compact current-task bar and workflow strip share a tight sticky header instead of being separated as independent chrome rows.",
            "When width allows, the compact current-task bar and workflow strip share one inline sticky row, reducing header height while keeping controls readable and tappable.",
            "On narrow compact viewports, the stacked current-task row stays low-profile while remaining touch-safe.",
            "The compact sticky task header is grouped inside a low-profile toolbar shell so the persistent task controls read as one toolbar.",
            "On narrow compact viewports, the compact sticky task header stacks into a dense current-task row plus one dense workflow row instead of a two-row workflow grid.",
            "The compact sticky task header reflows between inline and stacked task/workflow layouts after Android rotation or keyboard viewport changes.",
            "The compact active task or last compact scroll target re-anchors after Android rotation or keyboard viewport changes without stealing focus from keyboard input fields.",
            "portal clearly exposes the next action",
            "Compact section headers keep title and readable task cue in one dense row without restoring bulky repeated subtitle cards",
            "Compact section headers use explicit short task cues such as .*Steam account.*, .*Current code.*, .*Local files.*, and .*Play safely.* instead of clipped desktop subtitle sentences",
            "Password-manager suggestions",
            "Steam Guard",
            "Failed login",
            "Successful return",
            "Native integrated credential panel supported:",
            "Native credential fields Autofill hints configured:",
            "Steam credential web domain configured:",
            "Native credential panel inline status configured:",
            "Native credential panel keyboard-safe layout configured:",
            "Native credential panel IME inset scroll supported:",
            "Native credential panel touch-target layout configured:",
            "Launcher Android-readable warmup screen supported:",
            "Launcher Android-readable startup status card supported:",
            "Launcher native fallback diagnostics collapsed by default:",
            "Launcher native fallback responsive recovery rows supported:",
            "Launcher startup recovery structured compact actions supported:",
            "Native credential panel requests both Autofill fields:",
            "Native credential panel focus Autofill requests supported:",
            "Native credential panel task-led buttons supported:",
            "Native credential panel responsive action rows supported:",
            "Native credential panel orientation reflow supported:",
            "Native credential panel short-height copy supported:",
            "Native credential panel short-height reflow supported:",
            "Native credential panel IME height reflow supported:",
            "Native credential panel password visibility toggle supported:",
            "Native credential panel password-focus button supported:",
            "Native credential panel Back dismiss supported:",
            "Native credential panel dismiss retry supported:",
            "Native credential panel dismiss hides keyboard:",
            "Native credential panel suppresses pre-auth save prompt:",
            "Steam Guard one-shot code guidance supported:",
            "Failed-login retry guidance supported:",
            "Context-specific login recovery guidance supported:",
            "Native credential handoff popup supported:",
            "Password-manager suggestions device validated:",
            "Launcher portal UX model:",
            "Launcher status-led portal supported:",
            "Launcher phase-labeled status supported:",
            "Launcher structured status chip supported:",
            "Launcher guided next-action status supported:",
            "Launcher error-first guided status supported:",
            "Launcher compact plain-language status copy supported:",
            "Launcher titled state sections supported:",
            "Launcher safe first-run guidance supported:",
            "Launcher compact safe-flow guidance collapsible:",
            "Launcher compact low-profile safe-flow toggle supported:",
            "Launcher compact safe-flow toggle detail labels supported:",
            "Launcher compact structured safe-flow toggle labels supported:",
            "Launcher compact safe-flow bounded guide supported:",
            "Launcher compact active-task safe-flow suppression supported:",
            "Launcher mobile-first compact layout supported:",
            "Launcher compact dense panel padding supported:",
            "Launcher compact dense vertical rhythm supported:",
            "Launcher rounded scaled metrics supported:",
            "Launcher Android compact touch-scale floor supported:",
            "Launcher compact dynamic content width supported:",
            "Launcher tablet/wide content layout supported:",
            "Launcher top-anchored portal content supported:",
            "Launcher compact vertical status hero supported:",
            "Launcher compact low-profile status card supported:",
            "Launcher compact status headline row supported:",
            "Launcher compact stacked status headline supported:",
            "Launcher viewport-aware compact status headline reflow supported:",
            "Launcher compact stable status detail row supported:",
            "Launcher compact short status details supported:",
            "Launcher compact sticky workflow step strip supported:",
            "Launcher compact low-profile workflow step strip supported:",
            "Launcher compact low-profile two-column workflow step strip supported:",
            "Launcher compact workflow step direct navigation supported:",
            "Launcher compact narrow workflow single-row supported:",
            "Launcher compact visible workflow step labels supported:",
            "Launcher compact workflow step detail labels supported:",
            "Launcher compact workflow step number badges supported:",
            "Launcher compact workflow unified touch height supported:",
            "Launcher compact current-task jump supported:",
            "Launcher compact sticky current-task bar supported:",
            "Launcher compact low-profile current-task bar supported:",
            "Launcher compact dense inline current-task bar supported:",
            "Launcher compact current-task shared touch height supported:",
            "Launcher compact low-profile stacked current-task bar supported:",
            "Launcher compact current-task context labels supported:",
            "Launcher compact structured current-task labels supported:",
            "Launcher compact touch-safe sticky header controls supported:",
            "Launcher compact grouped sticky task header supported:",
            "Launcher compact sticky task toolbar shell supported:",
            "Launcher compact inline sticky task header supported:",
            "Launcher compact responsive sticky task header supported:",
            "Launcher viewport-aware sticky task header reflow supported:",
            "Launcher viewport-aware compact task re-anchor supported:",
            "Launcher compact dense sticky task header supported:",
            "Launcher compact task-jump navigation labels supported:",
            "Launcher compact padded scroll anchors supported:",
            "Launcher keyboard-focused input scroll supported:",
            "Launcher compact contextual confirmation labels supported:",
            "Launcher compact scroll-safe confirmation dialogs supported:",
            "Launcher viewport-aware confirmation dialogs supported:",
            "Launcher compact Steam Guard large input supported:",
            "Launcher compact Steam Guard action-first layout supported:",
            "Launcher compact Steam Guard inline action row supported:",
            "Launcher compact responsive Steam Guard action layout supported:",
            "Launcher viewport-aware compact Steam Guard action row reflow supported:",
            "Launcher compact Steam Guard submit detail label supported:",
            "Launcher compact Steam Guard retry guidance supported:",
            "Launcher compact Steam Guard bounded helper supported:",
            "Launcher compact primary retry action supported:",
            "Launcher compact structured retry action labels supported:",
            "Launcher compact primary login action first supported:",
            "Launcher compact Android login primary CTA supported:",
            "Launcher compact Android login detail label supported:",
            "Launcher compact Android login helper detail label supported:",
            "Launcher compact completed-auth section suppression supported:",
            "Launcher touch-first action targets supported:",
            "Launcher primary action wording supported:",
            "Launcher consistent Start Game CTA supported:",
            "Launcher compact launch detail label supported:",
            "Launcher branded atmospheric background supported:",
            "Launcher branded background explicit RGBA supported:",
            "Launcher high-contrast rounded actions supported:",
            "Launcher compact header chrome reduction supported:",
            "Launcher compact condensed brand header supported:",
            "Launcher compact single-line brand header supported:",
            "Launcher compact readable brand subtitle supported:",
            "The compact brand subtitle remains readable at phone scale and uses plain app copy instead of pipe-separated command-line-style labels.",
            "Launcher compact section-header subtitle suppression supported:",
            "Launcher compact low-profile section headers supported:",
            "Launcher compact single-row section headers supported:",
            "Launcher compact section-header task cues supported:",
            "Launcher compact readable section-header cues supported:",
            "Launcher compact explicit section-header cues supported:",
            "Launcher compact install primary detail label supported:",
            "Launcher compact download progress hero supported:",
            "Launcher compact download progress status label supported:",
            "Launcher compact readable download progress bar supported:",
            "Launcher compact inline install-version controls supported:",
            "Launcher compact version details collapsible:",
            "Launcher compact version drawer bounded help label supported:",
            "Launcher compact structured install-version action labels supported:",
            "Launcher compact version summary cards supported:",
            "Launcher compact selected-version summary shortcut supported:",
            "Launcher compact selected-version headline supported:",
            "Launcher compact responsive selected-version summary supported:",
            "Launcher compact ready-version summary panel supported:",
            "Launcher compact ready-version summary shortcut supported:",
            "Launcher compact ready-version headline supported:",
            "Launcher compact responsive ready-version summary supported:",
            "Launcher compact structured Play/Sync action labels supported:",
            "Launcher compact ready-state install-section suppression supported:",
            "Launcher compact touch-safe version dropdown supported:",
            "Launcher compact touch-safe dropdown popup supported:",
            "Launcher compact cloud-safety guidance collapsible:",
            "Launcher compact cloud-safety detail label supported:",
            "Launcher compact cloud options collapsible:",
            "Launcher primary cloud actions before cloud options:",
            "Launcher compact cloud option detail labels supported:",
            "Launcher safer Pull-before-Push cloud ordering supported:",
            "Launcher compact cloud direction labels supported:",
            "Launcher compact cloud primary actions row supported:",
            "Launcher compact Pull detail label supported:",
            "Launcher compact responsive action rows supported:",
            "Launcher compact dangerous Push detail labels supported:",
            "Launcher compact armed Push warning detail label supported:",
            "Launcher manual Push armed overwrite warning supported:",
            "Launcher compact cloud options row supported:",
            "Launcher version-install/cloud-save separation guidance supported:",
            "Launcher Help & Reports drawer hidden by default:",
            "Launcher Help & Reports drawer auto-opens for diagnostics actions:",
            "Compact diagnostics toggle renders .*Help & Reports.*Private until opened.*structured title/detail labels",
            "Launcher compact low-profile drawer toggles supported:",
            "Launcher compact dense drawer toggle height supported:",
            "Launcher compact support tools grid supported:",
            "Launcher compact launcher-log review label supported:",
            "Launcher plain-language help report copy supported:",
            "Launcher startup recovery structured compact actions supported:",
            "Launcher compact low-profile diagnostics toggle supported:",
            "Launcher compact diagnostics toggle detail labels supported:",
            "Launcher compact structured diagnostics toggle labels supported:",
            "Launcher startup fallback raw banner suppressed:",
            "Launcher portal UX device validated:",
            "Launcher portal UX validation boundary:",
            "SteamKit debug logs sanitized for credentials/tokens:",
            "portal scaling/readability/next-action clarity",
            "hidden diagnostics behavior",
            "not complete until ARM64 evidence covers"
        )
}
