<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>../../upstream/godot-export/.godot/mono/publish/arm64/0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>../../android/assets/dotnet_bcl/Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>../../android/assets/dotnet_bcl/Mono.Cecil.Mdb.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>../../android/assets/dotnet_bcl/Mono.Cecil.Pdb.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>../../android/assets/dotnet_bcl/Mono.Cecil.Rocks.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Backports">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Backports.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Core">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Iced">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Iced.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.ILHelpers">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.ILHelpers.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>../../android/assets/dotnet_bcl/MonoMod.Utils.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
